import { WorkerProfile } from "@/types";
import { BookingDoc, AdminStats } from "@/types/firestore";

export const DEMO_WORKERS: WorkerProfile[] = [
  {
    id: "demo-w1",
    name: "Rajesh Kumar",
    category: "Electrician",
    categorySlug: "electrician",
    rating: 4.8,
    reviewCount: 127,
    experience: 12,
    distance: "2.5 km",
    hourlyRate: 450,
    isVerified: true,
    isAvailable: true,
    image: "https://ui-avatars.com/api/?name=Rajesh+Kumar&background=3b82f6&color=fff",
    location: "Gomti Nagar, Lucknow",
    skills: ["Wiring", "AC Repair", "Fans", "Lighting"],
    description: "Experienced electrician with 12+ years. Specialized in AC repair and wiring.",
    languages: ["Hindi", "English", "Urdu"],
    availability: "Mon-Fri 9am-6pm",
    joinedDate: "2023-08-15",
    portfolioImages: [],
    reviews: [],
  },
  {
    id: "demo-w2",
    name: "Priya Sharma",
    category: "Plumber",
    categorySlug: "plumber",
    rating: 4.6,
    reviewCount: 89,
    experience: 8,
    distance: "1.2 km",
    hourlyRate: 350,
    minVisitCharge: 200,
    isVerified: true,
    isAvailable: true,
    image: "https://ui-avatars.com/api/?name=Priya+Sharma&background=10b981&color=fff",
    location: "Indiranagar, Lucknow",
    skills: ["Pipes", "Bathroom", "Leak Repair", "Drainage"],
    description: "Reliable plumber for all residential and commercial needs.",
    languages: ["Hindi", "English"],
    availability: "Mon-Sat 8am-7pm",
    joinedDate: "2023-12-03",
    portfolioImages: [],
    reviews: [],
  },
  {
    id: "demo-w3",
    name: "Amit Verma",
    category: "AC Repair",
    categorySlug: "ac-repair",
    rating: 4.9,
    reviewCount: 156,
    experience: 15,
    distance: "4.1 km",
    hourlyRate: 600,
    isVerified: true,
    isAvailable: false,
    image: "https://ui-avatars.com/api/?name=Amit+Verma&background=f59e0b&color=fff",
    location: "Alambagh, Lucknow",
    skills: ["AC Installation", "Gas Refill", "Maintenance", "Dryer Cleaning"],
    description: "15+ years experience in AC repair and maintenance. Same-day service available.",
    languages: ["Hindi", "English", "Awadhi"],
    availability: "By appointment",
    joinedDate: "2023-05-20",
    portfolioImages: [],
    reviews: [],
  },
  {
    id: "demo-w4",
    name: "Sneha Patel",
    category: "House Cleaner",
    categorySlug: "house-cleaner",
    rating: 4.3,
    reviewCount: 64,
    experience: 5,
    distance: "3.0 km",
    hourlyRate: 300,
    isVerified: true,
    isAvailable: true,
    image: "https://ui-avatars.com/api/?name=Sneha+Patel&background=ef4444&color=fff",
    location: "Gomti Nagar, Lucknow",
    skills: ["Deep Cleaning", "Kitchen", "Bathroom", "Office Cleaning"],
    description: "Professional house cleaner with attention to detail.",
    languages: ["Hindi", "English", "Gujarati"],
    availability: "Mon-Fri 7am-5pm",
    joinedDate: "2024-01-10",
    portfolioImages: [],
    reviews: [],
  },
  {
    id: "demo-w5",
    name: "Manoj Tiwari",
    category: "Carpenter",
    categorySlug: "carpenter",
    rating: 4.5,
    reviewCount: 43,
    experience: 10,
    distance: "5.7 km",
    hourlyRate: 400,
    isVerified: true,
    isAvailable: true,
    image: "https://ui-avatars.com/api/?name=Manoj+Tiwari&background=8b5cf6&color=fff",
    location: "Indiranagar, Lucknow",
    skills: ["Furniture", "Cabinets", "Doors", "Windows"],
    description: "Skilled carpenter for custom furniture and repairs.",
    languages: ["Hindi", "English"],
    availability: "Mon-Sat 9am-6pm",
    joinedDate: "2023-09-18",
    portfolioImages: [],
    reviews: [],
  },
];

export const DEMO_BOOKINGS: BookingDoc[] = [
  {
    id: "demo-b1",
    customerId: "demo-user-1",
    workerId: "demo-w1",
    workerName: "Rajesh Kumar",
    workerImage: "https://ui-avatars.com/api/?name=Rajesh+Kumar&background=3b82f6&color=fff",
    customerName: "You",
    service: "Electrician - Fan Installation",
    description: "Need ceiling fan installed in bedroom",
    date: "2025-01-20",
    time: "10:00 AM",
    address: "123 Main Street, Gomti Nagar",
    landmark: "Near HDFC Bank",
    notes: "Please bring a sturdy ladder",
    duration: "1hr",
    status: "completed",
    totalAmount: 500,
    amount: 500,
    earnings: 450,
    createdAt: new Date("2025-01-15"),
    updatedAt: new Date("2025-01-20"),
  },
  {
    id: "demo-b2",
    customerId: "demo-user-1",
    workerId: "demo-w2",
    workerName: "Priya Sharma",
    workerImage: "https://ui-avatars.com/api/?name=Priya+Sharma&background=10b981&color=fff",
    customerName: "You",
    service: "Plumber - Bathroom Leak",
    description: "Kitchen sink leaking",
    date: "2025-01-22",
    time: "02:00 PM",
    address: "456 Park Avenue, Indiranagar",
    landmark: "Green Park",
    notes: "",
    duration: "2hr",
    status: "accepted",
    totalAmount: 800,
    amount: 800,
    earnings: 700,
    createdAt: new Date("2025-01-20"),
    updatedAt: new Date("2025-01-21"),
  },
  {
    id: "demo-b3",
    customerId: "demo-user-1",
    workerId: "demo-w3",
    workerName: "Amit Verma",
    workerImage: "https://ui-avatars.com/api/?name=Amit+Verma&background=f59e0b&color=fff",
    customerName: "You",
    service: "AC Repair - Not Cooling",
    description: "AC gas refilling needed",
    date: "2025-01-25",
    time: "11:00 AM",
    address: "789 Lake View, Alambagh",
    landmark: "Alambagh Crossing",
    notes: "Window AC, 1.5 ton",
    duration: "2hr",
    status: "pending",
    totalAmount: 1200,
    amount: 1200,
    earnings: 1000,
    createdAt: new Date("2025-01-22"),
    updatedAt: new Date("2025-01-22"),
  },
  {
    id: "demo-b4",
    customerId: "demo-user-1",
    workerId: "demo-w4",
    workerName: "Sneha Patel",
    workerImage: "https://ui-avatars.com/api/?name=Sneha+Patel&background=ef4444&color=fff",
    customerName: "You",
    service: "House Cleaning - Deep Clean",
    description: "Full house deep cleaning",
    date: "2025-01-10",
    time: "09:00 AM",
    address: "123 Main Street, Gomti Nagar",
    landmark: "Near HDFC Bank",
    notes: "",
    duration: "4hr",
    status: "completed",
    totalAmount: 1500,
    amount: 1500,
    earnings: 1300,
    createdAt: new Date("2025-01-08"),
    updatedAt: new Date("2025-01-10"),
  },
  {
    id: "demo-b5",
    customerId: "demo-user-1",
    workerId: "demo-w5",
    workerName: "Manoj Tiwari",
    workerImage: "https://ui-avatars.com/api/?name=Manoj+Tiwari&background=8b5cf6&color=fff",
    customerName: "You",
    service: "Carpenter - Shelf Installation",
    description: "Install wooden shelves in living room",
    date: "2025-01-05",
    time: "03:00 PM",
    address: "456 Park Avenue, Indiranagar",
    landmark: "Green Park",
    notes: "",
    duration: "2hr",
    status: "cancelled",
    totalAmount: 600,
    amount: 600,
    earnings: 0,
    createdAt: new Date("2025-01-03"),
    updatedAt: new Date("2025-01-05"),
  },
];

export const DEMO_STATS: AdminStats = {
  totalUsers: 156,
  totalWorkers: 89,
  verifiedWorkers: 67,
  pendingVerifications: 12,
  activeBookings: 45,
  completedBookings: 297,
  totalTransactions: 120,
  activeAdvertisements: 8,
};
