import {
  Category,
  WorkerProfile,
  Testimonial,
  FAQ,
  Step,
  Statistic,
  Feature,
  Review,
} from "@/types";

export const CATEGORIES: Category[] = [
  { id: "1", name: "Electrician", slug: "electrician", icon: "Zap", description: "Wiring, repairs, installations", workerCount: 245, image: "/images/categories/electrician.jpg" },
  { id: "2", name: "Plumber", slug: "plumber", icon: "Wrench", description: "Pipes, fittings, drainage", workerCount: 189, image: "/images/categories/plumber.jpg" },
  { id: "3", name: "Painter", slug: "painter", icon: "Paintbrush", description: "Interior, exterior, texture", workerCount: 156, image: "/images/categories/painter.jpg" },
  { id: "4", name: "Carpenter", slug: "carpenter", icon: "Hammer", description: "Furniture, fittings, repair", workerCount: 134, image: "/images/categories/carpenter.jpg" },
  { id: "5", name: "Mechanic", slug: "mechanic", icon: "Settings", description: "Vehicle repair, service", workerCount: 112, image: "/images/categories/mechanic.jpg" },
  { id: "6", name: "Driver", slug: "driver", icon: "Car", description: "Personal, commercial, cab", workerCount: 298, image: "/images/categories/driver.jpg" },
  { id: "7", name: "Cleaner", slug: "cleaner", icon: "Sparkles", description: "Home, office, deep clean", workerCount: 167, image: "/images/categories/cleaner.jpg" },
  { id: "8", name: "Construction Labour", slug: "construction-labour", icon: "HardHat", description: "Mason, helper, site work", workerCount: 203, image: "/images/categories/construction.jpg" },
  { id: "9", name: "AC Repair", slug: "ac-repair", icon: "Snowflake", description: "Installation, service, gas", workerCount: 89, image: "/images/categories/ac-repair.jpg" },
  { id: "10", name: "RO Repair", slug: "ro-repair", icon: "Droplets", description: "Purifier service, filter change", workerCount: 76, image: "/images/categories/ro-repair.jpg" },
  { id: "11", name: "Welder", slug: "welder", icon: "Flame", description: "Metal welding, fabrication", workerCount: 64, image: "/images/categories/welder.jpg" },
  { id: "12", name: "Mason", slug: "mason", icon: "Layers", description: "Brick work, plastering, tiling", workerCount: 91, image: "/images/categories/mason.jpg" },
  { id: "13", name: "House Maid", slug: "house-maid", icon: "Home", description: "Cleaning, cooking, babysitting", workerCount: 210, image: "/images/categories/housemaid.jpg" },
  { id: "14", name: "Cook", slug: "cook", icon: "ChefHat", description: "Home cook, catering, tiffin", workerCount: 145, image: "/images/categories/cook.jpg" },
  { id: "15", name: "Tutor", slug: "tutor", icon: "BookOpen", description: "Home tuition, exam prep", workerCount: 178, image: "/images/categories/tutor.jpg" },
  { id: "16", name: "Photographer", slug: "photographer", icon: "Camera", description: "Event, wedding, portfolio", workerCount: 56, image: "/images/categories/photographer.jpg" },
  { id: "17", name: "Internet Technician", slug: "internet-technician", icon: "Wifi", description: "WiFi setup, router, broadband", workerCount: 42, image: "/images/categories/internet-technician.jpg" },
];

const makeReview = (id: string, userName: string, userAvatar: string, rating: number, comment: string, date: string): Review => ({
  id, userName, userAvatar, rating, comment, date,
});

const makeWorker = (id: string, name: string, category: string, categorySlug: string, rating: number, reviewCount: number, experience: number, distance: string, hourlyRate: number, isVerified: boolean, isAvailable: boolean, image: string, location: string, skills: string[], description: string, languages: string[], availability: string, joinedDate: string, portfolioImages: string[], reviews: Review[]): WorkerProfile => ({
  id, name, category, categorySlug, rating, reviewCount, experience, distance, hourlyRate, isVerified, isAvailable, image, location, skills, description, languages, availability, joinedDate, portfolioImages, reviews,
});

export const WORKERS: WorkerProfile[] = [
  makeWorker("1", "Ramesh Kumar", "Electrician", "electrician", 4.8, 127, 12, "2.3 km", 350, true, true, "/images/workers/worker-1.jpg", "Sector 12, Noida", ["Wiring", "Panel Board", "LED Installation"], "Experienced electrician with 12+ years in residential and commercial wiring.", ["Hindi", "English"], "Mon-Sat, 9AM-7PM", "2022-03-15", ["/images/workers/portfolio/1a.jpg", "/images/workers/portfolio/1b.jpg"], [makeReview("r1", "Priya Mehta", "/images/testimonials/avatar-1.jpg", 5, "Excellent work! Very professional and punctual.", "2024-01-10")]),
  makeWorker("2", "Suresh Yadav", "Plumber", "plumber", 4.6, 89, 8, "1.8 km", 280, true, true, "/images/workers/worker-2.jpg", "Indirapuram, Ghaziabad", ["Pipe Fitting", "Water Heater", "Leakage"], "Reliable plumber specializing in bathroom fittings and pipe repairs.", ["Hindi", "English"], "Mon-Sat, 8AM-6PM", "2023-01-20", ["/images/workers/portfolio/2a.jpg"], [makeReview("r2", "Rahul Gupta", "/images/testimonials/avatar-2.jpg", 4, "Good service. Fixed the leak in one visit.", "2024-02-05")]),
  makeWorker("3", "Amit Sharma", "Painter", "painter", 4.9, 156, 15, "3.1 km", 400, true, false, "/images/workers/worker-3.jpg", "DLF Phase 2, Gurgaon", ["Interior Painting", "Texture", "Wallpaper"], "Professional painter with expertise in Asian Paints and Berger textures.", ["Hindi", "English", "Punjabi"], "Tue-Sun, 10AM-8PM", "2021-06-10", ["/images/workers/portfolio/3a.jpg", "/images/workers/portfolio/3b.jpg"], [makeReview("r3", "Anjali Singh", "/images/testimonials/avatar-3.jpg", 5, "Amazing texture work! Highly recommended.", "2024-03-12")]),
  makeWorker("4", "Vijay Singh", "Carpenter", "carpenter", 4.7, 94, 10, "2.7 km", 320, true, true, "/images/workers/worker-4.jpg", "Rajouri Garden, Delhi", ["Furniture", "Kitchen", "Door Fitting"], "Skilled carpenter for custom furniture and modular kitchen installations.", ["Hindi", "English"], "Mon-Sat, 9AM-6PM", "2022-08-05", ["/images/workers/portfolio/4a.jpg"], [makeReview("r4", "Vikram Joshi", "/images/testimonials/avatar-4.jpg", 5, "Great craftsmanship on our new kitchen cabinets.", "2024-01-22")]),
  makeWorker("5", "Prakash Verma", "AC Repair", "ac-repair", 4.5, 67, 6, "4.2 km", 450, true, true, "/images/workers/worker-5.jpg", "Vaishali, Ghaziabad", ["Split AC", "Window AC", "Gas Refill"], "Certified AC technician for all brands. Gas refill and AMC available.", ["Hindi", "English"], "Mon-Sun, 8AM-9PM", "2023-05-18", ["/images/workers/portfolio/5a.jpg", "/images/workers/portfolio/5b.jpg"], [makeReview("r5", "Neha Kapoor", "/images/testimonials/avatar-1.jpg", 5, "Quick service and reasonable charges.", "2024-02-14")]),
  makeWorker("6", "Deepak Rathi", "Driver", "driver", 4.4, 45, 5, "1.5 km", 200, true, true, "/images/workers/worker-6.jpg", "Mayur Vihar, Delhi", ["Manual", "Auto", "Long Distance"], "Professional driver with clean record. Familiar with Delhi NCR routes.", ["Hindi", "English"], "24/7 Available", "2023-09-01", ["/images/workers/portfolio/6a.jpg"], [makeReview("r6", "Amit Jain", "/images/testimonials/avatar-2.jpg", 4, "Smooth driving and on-time pickup.", "2024-03-01")]),
  makeWorker("7", "Mohan Lal", "Welder", "welder", 4.3, 34, 14, "5.1 km", 380, true, true, "/images/workers/worker-7.jpg", "Faridabad, Haryana", ["MIG Welding", "TIG Welding", "Fabrication"], "Expert welder with 14 years in industrial and residential metal work.", ["Hindi", "Haryanvi"], "Mon-Sat, 8AM-5PM", "2022-11-20", ["/images/workers/portfolio/7a.jpg", "/images/workers/portfolio/7b.jpg"], [makeReview("r7", "Sunit Kumar", "/images/testimonials/avatar-3.jpg", 5, "Strong and clean welds. Very satisfied.", "2024-01-18")]),
  makeWorker("8", "Raju Thakur", "Mason", "mason", 4.5, 56, 18, "3.4 km", 420, true, true, "/images/workers/worker-8.jpg", "Laxmi Nagar, Delhi", ["Brick Work", "Plastering", "Tiling"], "Senior mason specializing in construction and renovation projects.", ["Hindi", "English"], "Mon-Sat, 7AM-5PM", "2021-04-12", ["/images/workers/portfolio/8a.jpg"], [makeReview("r8", "Kavita Singh", "/images/testimonials/avatar-4.jpg", 4, "Good quality tile work at reasonable price.", "2024-02-28")]),
  makeWorker("9", "Sunita Devi", "House Maid", "house-maid", 4.7, 112, 7, "1.2 km", 180, true, true, "/images/workers/worker-9.jpg", "Vasundhara, Ghaziabad", ["Cleaning", "Cooking", "Babysitting"], "Trusted maid for full-time and part-time house help.", ["Hindi", "Bhojpuri"], "Mon-Sat, 9AM-5PM", "2023-02-14", ["/images/workers/portfolio/9a.jpg", "/images/workers/portfolio/9b.jpg"], [makeReview("r9", "Ritu Sharma", "/images/testimonials/avatar-1.jpg", 5, "Very hardworking and honest. Highly recommended.", "2024-03-05")]),
  makeWorker("10", "Kishore Pandey", "Cook", "cook", 4.6, 78, 9, "2.9 km", 250, true, true, "/images/workers/worker-10.jpg", "Sahibabad, Ghaziabad", ["North Indian", "South Indian", "Chinese"], "Home chef specializing in daily meals and party catering.", ["Hindi", "English"], "Mon-Sun, 7AM-10AM, 12PM-2PM, 7PM-9PM", "2022-07-01", ["/images/workers/portfolio/10a.jpg"], [makeReview("r10", "Anil Verma", "/images/testimonials/avatar-2.jpg", 4, "Delicious food and hygienic cooking.", "2024-01-30")]),
  makeWorker("11", "Sanjay Gupta", "Mechanic", "mechanic", 4.4, 62, 11, "3.8 km", 300, true, true, "/images/workers/worker-11.jpg", "Okhla, Delhi", ["Car Repair", "Bike Repair", "Engine Overhaul"], "Experienced mechanic for all two-wheelers and four-wheelers.", ["Hindi", "English"], "Mon-Sat, 9AM-8PM", "2022-01-15", ["/images/workers/portfolio/11a.jpg", "/images/workers/portfolio/11b.jpg"], [makeReview("r11", "Pankaj Singh", "/images/testimonials/avatar-3.jpg", 4, "Resolved engine issue quickly.", "2024-02-10")]),
  makeWorker("12", "Rekha Sharma", "Tutor", "tutor", 4.9, 143, 8, "0.8 km", 500, true, true, "/images/workers/worker-12.jpg", "Hauz Khas, Delhi", ["Mathematics", "Physics", "JEE Prep"], "Expert tutor for classes 9-12 and JEE/NEET preparation.", ["Hindi", "English"], "Mon-Sat, 4PM-8PM", "2021-09-01", ["/images/workers/portfolio/12a.jpg"], [makeReview("r12", "Suman Joshi", "/images/testimonials/avatar-4.jpg", 5, "My child's grades improved significantly.", "2024-03-15")]),
  makeWorker("13", "Vikram Photographer", "Photographer", "photographer", 4.7, 89, 7, "4.5 km", 8000, true, true, "/images/workers/worker-13.jpg", "Connaught Place, Delhi", ["Wedding", "Event", "Pre-wedding"], "Creative photographer capturing life's beautiful moments.", ["Hindi", "English"], "On Request", "2020-05-20", ["/images/workers/portfolio/13a.jpg", "/images/workers/portfolio/13b.jpg"], [makeReview("r13", "Pooja Malhotra", "/images/testimonials/avatar-1.jpg", 5, "Stunning wedding album!", "2024-01-05")]),
  makeWorker("14", "Anil Kumar", "RO Repair", "ro-repair", 4.4, 53, 5, "2.1 km", 300, true, true, "/images/workers/worker-14.jpg", "Preet Vihar, Delhi", ["RO Service", "Filter Change", "AMC"], "RO specialist for all major brands with genuine spare parts.", ["Hindi", "English"], "Mon-Sat, 10AM-7PM", "2023-03-10", ["/images/workers/portfolio/14a.jpg"], [makeReview("r14", "Meera Iyer", "/images/testimonials/avatar-2.jpg", 4, "Prompt service and good parts.", "2024-02-20")]),
  makeWorker("15", "Dinesh Rathore", "Cleaner", "cleaner", 4.5, 98, 6, "1.6 km", 220, true, true, "/images/workers/worker-15.jpg", "Lajpat Nagar, Delhi", ["Home Cleaning", "Office Cleaning", "Deep Cleaning"], "Professional cleaner providing spotless results every time.", ["Hindi", "English"], "Mon-Sun, 8AM-8PM", "2022-12-01", ["/images/workers/portfolio/15a.jpg", "/images/workers/portfolio/15b.jpg"], [makeReview("r15", "Rohit Sehgal", "/images/testimonials/avatar-3.jpg", 5, "Very thorough deep cleaning.", "2024-03-08")]),
  makeWorker("16", "Bharat Singh", "Electrician", "electrician", 4.2, 45, 6, "3.6 km", 280, false, true, "/images/workers/worker-16.jpg", "Kaushambi, Ghaziabad", ["Wiring", "Fan Installation", "Switch Repair"], "Friendly electrician for small repairs and installations.", ["Hindi"], "Mon-Sat, 10AM-6PM", "2023-08-15", ["/images/workers/portfolio/16a.jpg"], [makeReview("r16", "Sunil Dagar", "/images/testimonials/avatar-4.jpg", 4, "Decent work for the price.", "2024-01-25")]),
  makeWorker("17", "Kavita Housekeeping", "Cleaner", "cleaner", 4.8, 134, 10, "0.9 km", 260, true, false, "/images/workers/worker-17.jpg", "Vasant Kunj, Delhi", ["Sofa Cleaning", "Carpet Cleaning", "Pest Control"], "Premium cleaning services with modern equipment.", ["Hindi", "English"], "Mon-Sun, 9AM-7PM", "2021-11-05", ["/images/workers/portfolio/17a.jpg", "/images/workers/portfolio/17b.jpg"], [makeReview("r17", "Aarti Bansal", "/images/testimonials/avatar-1.jpg", 5, "Best cleaning service in the area!", "2024-02-12")]),
  makeWorker("18", "Rahul Mechanic", "Mechanic", "mechanic", 4.1, 38, 7, "4.8 km", 260, true, true, "/images/workers/worker-18.jpg", "Badarpur, Delhi", ["Bike Repair", "Car Service", "Oil Change"], "Affordable mechanic for routine servicing and repairs.", ["Hindi", "English"], "Mon-Sat, 9AM-7PM", "2023-06-20", ["/images/workers/portfolio/18a.jpg"], [makeReview("r18", "Deepak Choudhary", "/images/testimonials/avatar-2.jpg", 4, "Budget-friendly service.", "2024-01-15")]),
  makeWorker("19", "Pooja Tutor", "Tutor", "tutor", 4.6, 67, 5, "1.1 km", 400, true, true, "/images/workers/worker-19.jpg", "Greater Kailash, Delhi", ["English", "Social Studies", "Competitive Exams"], "Dedicated tutor for school students and competitive exam preparation.", ["Hindi", "English"], "Mon-Fri, 4PM-7PM", "2023-01-10", ["/images/workers/portfolio/19a.jpg", "/images/workers/portfolio/19b.jpg"], [makeReview("r19", "Richa Arora", "/images/testimonials/avatar-3.jpg", 5, "Very patient and knowledgeable.", "2024-03-01")]),
  makeWorker("20", "Gopal Driver", "Driver", "driver", 4.3, 52, 9, "2.5 km", 250, true, true, "/images/workers/worker-20.jpg", "Dwarka, Delhi", ["Maruti", "Hyundai", "Long Distance"], "Experienced driver for office commute and outstation trips.", ["Hindi", "English"], "24/7 Available", "2022-04-01", ["/images/workers/portfolio/20a.jpg"], [makeReview("r20", "Naveen Tyagi", "/images/testimonials/avatar-4.jpg", 4, "Safe and smooth ride.", "2024-02-18")]),
  makeWorker("21", "Lalita Cook", "Cook", "cook", 4.7, 91, 12, "1.3 km", 280, true, true, "/images/workers/worker-21.jpg", "Pitampura, Delhi", ["Rajasthani", "Gujarati", "Punjabi"], "Specialty in North Indian and traditional home-cooked meals.", ["Hindi", "English"], "Mon-Sat, 8AM-12PM, 1PM-4PM", "2022-02-28", ["/images/workers/portfolio/21a.jpg", "/images/workers/portfolio/21b.jpg"], [makeReview("r21", "Shalini Jindal", "/images/testimonials/avatar-1.jpg", 5, "Authentic taste like home!", "2024-01-28")]),
  makeWorker("22", "Birju Carpenter", "Carpenter", "carpenter", 4.0, 29, 6, "4.1 km", 250, false, true, "/images/workers/worker-22.jpg", "Burari, Delhi", ["Furniture Repair", "Door Fitting", "Shelf Installation"], "Budget carpenter for small repairs and fittings.", ["Hindi"], "Mon-Sat, 9AM-5PM", "2023-10-01", ["/images/workers/portfolio/22a.jpg"], [makeReview("r22", "Manoj Pandey", "/images/testimonials/avatar-2.jpg", 4, "Good for minor fixes.", "2024-02-02")]),
  makeWorker("23", "Nitin Painter", "Painter", "painter", 4.3, 48, 9, "2.8 km", 320, true, true, "/images/workers/worker-23.jpg", "Rohini, Delhi", ["Interior Painting", "Exterior Painting", "Wall Putty"], "Reliable painter for home and office spaces.", ["Hindi", "English"], "Mon-Sat, 9AM-6PM", "2022-09-15", ["/images/workers/portfolio/23a.jpg", "/images/workers/portfolio/23b.jpg"], [makeReview("r23", "Sandeep Malik", "/images/testimonials/avatar-3.jpg", 4, "Clean finish and on-time delivery.", "2024-01-20")]),
  makeWorker("24", "Rajesh Plumber", "Plumber", "plumber", 4.1, 41, 7, "3.3 km", 260, false, true, "/images/workers/worker-24.jpg", "Saraswati Vihar, Delhi", ["Pipe Repair", "Tap Installation", "Drain Cleaning"], "Local plumber for quick fixes and installations.", ["Hindi"], "Mon-Sat, 10AM-6PM", "2023-04-01", ["/images/workers/portfolio/24a.jpg"], [makeReview("r24", "Vinod Kumar", "/images/testimonials/avatar-4.jpg", 4, "Fixed the issue quickly.", "2024-03-10")]),
  makeWorker("25", "Sachin Driver", "Driver", "driver", 4.6, 73, 8, "1.9 km", 280, true, true, "/images/workers/worker-25.jpg", "Nehru Place, Delhi", ["Sedan", "SUV", "Outstation"], "Professional driver for corporate and personal use.", ["Hindi", "English"], "24/7 Available", "2022-06-01", ["/images/workers/portfolio/25a.jpg", "/images/workers/portfolio/25b.jpg"], [makeReview("r25", "Tarun Sethi", "/images/testimonials/avatar-1.jpg", 5, "Excellent long-distance driving skills.", "2024-02-25")]),
  makeWorker("26", "Meera Housekeeping", "House Maid", "house-maid", 4.4, 76, 5, "2.4 km", 200, true, true, "/images/workers/worker-26.jpg", "Malviya Nagar, Delhi", ["Cleaning", "Utensil Cleaning", "Dusting"], "Part-time maid available for daily cleaning tasks.", ["Hindi", "English"], "Mon-Sat, 10AM-2PM", "2023-07-15", ["/images/workers/portfolio/26a.jpg"], [makeReview("r26", "Divya Rana", "/images/testimonials/avatar-2.jpg", 4, "Punctual and hardworking.", "2024-01-12")]),
  makeWorker("27", "Arjun Mason", "Mason", "mason", 4.2, 37, 13, "5.3 km", 380, true, true, "/images/workers/worker-27.jpg", "Najafgarh, Delhi", ["Brick Work", "Concrete", "Plastering"], "Experienced mason for new construction and renovation.", ["Hindi", "Haryanvi"], "Mon-Sat, 7AM-5PM", "2021-12-10", ["/images/workers/portfolio/27a.jpg", "/images/workers/portfolio/27b.jpg"], [makeReview("r27", "Rajinder Singh", "/images/testimonials/avatar-3.jpg", 4, "Good quality brickwork.", "2024-02-08")]),
  makeWorker("28", "Imran AC Tech", "AC Repair", "ac-repair", 4.0, 41, 7, "3.9 km", 400, true, true, "/images/workers/worker-28.jpg", "Jamia Nagar, Delhi", ["Window AC", "Split AC", "Cooling Issue"], "Affordable AC repair and maintenance services.", ["Hindi", "Urdu", "English"], "Mon-Sun, 9AM-9PM", "2023-02-01", ["/images/workers/portfolio/28a.jpg"], [makeReview("r28", "Faisal Khan", "/images/testimonials/avatar-4.jpg", 4, "Good rates and quick fix.", "2024-01-30")]),
  makeWorker("29", "Ravi Tutor", "Tutor", "tutor", 4.3, 54, 6, "2.0 km", 350, true, true, "/images/workers/worker-29.jpg", "Mayur Vihar Phase 1, Delhi", ["Science", "Computer", "Spoken English"], "Friendly tutor for school kids and spoken English.", ["Hindi", "English"], "Mon-Fri, 5PM-8PM", "2023-05-01", ["/images/workers/portfolio/29a.jpg", "/images/workers/portfolio/29b.jpg"], [makeReview("r29", "Komal Aggarwal", "/images/testimonials/avatar-1.jpg", 4, "My kid enjoys the classes.", "2024-03-02")]),
  makeWorker("30", "Suman Electrician", "Electrician", "electrician", 4.5, 61, 9, "2.6 km", 320, true, true, "/images/workers/worker-30.jpg", "Janakpuri, Delhi", ["Home Wiring", "Inverter", "Solar Panel"], "Expert in home electrical systems and solar installations.", ["Hindi", "English"], "Mon-Sat, 9AM-7PM", "2022-05-20", ["/images/workers/portfolio/30a.jpg"], [makeReview("r30", "Vivek Bhatia", "/images/testimonials/avatar-2.jpg", 5, "Installed solar panels efficiently.", "2024-01-08")]),
];

export const TESTIMONIALS: Testimonial[] = [
  { id: "1", name: "Priya Mehta", role: "Homeowner", avatar: "/images/testimonials/avatar-1.jpg", content: "Found an amazing electrician within minutes. The worker was verified, professional, and finished the job on time. Highly recommend KaamWala!", rating: 5 },
  { id: "2", name: "Rahul Gupta", role: "Business Owner", avatar: "/images/testimonials/avatar-2.jpg", content: "We use KaamWala for all our office maintenance needs. The quality of workers is consistently excellent and pricing is transparent.", rating: 5 },
  { id: "3", name: "Anjali Singh", role: "Rental Property Manager", avatar: "/images/testimonials/avatar-3.jpg", content: "Managing multiple properties is now so much easier. KaamWala connects us with reliable workers instantly. The verification process gives us peace of mind.", rating: 4 },
  { id: "4", name: "Vikram Joshi", role: "Restaurant Owner", avatar: "/images/testimonials/avatar-4.jpg", content: "The platform is incredibly easy to use. I needed a plumber urgently and found one within 2km. The worker arrived on time and did a great job.", rating: 5 },
];

export const FAQS: FAQ[] = [
  { id: "1", question: "How do I find a worker on KaamWala?", answer: "Simply search for the service you need, browse verified workers near you, check their ratings and experience, and book instantly. You can also call or WhatsApp them directly." },
  { id: "2", question: "Are all workers verified?", answer: "Yes, every worker on KaamWala goes through a thorough verification process including ID verification, skill assessment, and background checks to ensure your safety." },
  { id: "3", question: "How much does it cost to hire a worker?", answer: "Costs vary by service type, worker experience, and job complexity. You can view hourly rates upfront before booking. There are no hidden charges." },
  { id: "4", question: "Can I cancel or reschedule a booking?", answer: "Yes, you can cancel or reschedule bookings up to 2 hours before the scheduled time without any cancellation fee." },
  { id: "5", question: "Is my payment secure?", answer: "Absolutely. We use secure payment gateways with bank-grade encryption. You can pay online or cash on service completion." },
  { id: "6", question: "Do workers come with tools and materials?", answer: "Most workers bring basic tools. For specific materials or special equipment, you can discuss with the worker beforehand or request them to bring it at an additional cost." },
];

export const HOW_IT_WORKS: Step[] = [
  { id: 1, title: "Search", description: "Enter the service you need and your location. Browse through verified workers near you.", icon: "Search" },
  { id: 2, title: "Choose", description: "Compare workers by ratings, experience, distance, and price. Read reviews from other customers.", icon: "CheckCircle" },
  { id: 3, title: "Hire", description: "Book instantly, call, or send a WhatsApp message. The worker arrives at your doorstep ready to work.", icon: "Users" },
];

export const STATISTICS: Statistic[] = [
  { id: 1, value: "10,000+", label: "Verified Workers", suffix: "+" },
  { id: 2, value: "5,000+", label: "Happy Customers", suffix: "+" },
  { id: 3, value: "100+", label: "Cities Covered", suffix: "+" },
  { id: 4, value: "50,000+", label: "Jobs Completed", suffix: "+" },
];

export const FEATURES: Feature[] = [
  { id: 1, title: "Verified Workers", description: "Every worker undergoes rigorous background checks and skill verification for your safety and peace of mind.", icon: "ShieldCheck" },
  { id: 2, title: "Fast Hiring", description: "Find and book workers in under 2 minutes. No waiting, no hassle. Get the help you need instantly.", icon: "Zap" },
  { id: 3, title: "Secure Payments", description: "Pay online or cash on completion. All transactions are secured with industry-standard encryption.", icon: "Lock" },
  { id: 4, title: "Nearby Search", description: "Discover skilled workers in your neighborhood. Save time with location-based search and matching.", icon: "MapPin" },
];
